    <script src="{{ asset('assets/client/vendor/jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/jquery-migrate.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/jquery.easing.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/jquery.back-to-top.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/jquery.smooth-scroll.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/jquery.wow.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/swiper/js/swiper.jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/masonry/jquery.masonry.pkgd.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/vendor/masonry/imagesloaded.pkgd.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/js/layout.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/js/components/wow.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/js/components/swiper.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/client/js/components/masonry.min.js') }}" type="text/javascript"></script>